name: weight_slider
description: Customisable slider widget for retrieving a person's weight/mass.
version: 1.1.0
homepage: https://covalsolutions.com
repository: https://github.com/coval-solutions/weight-slider
issue_tracker: https://github.com/coval-solutions/weight-slider/issues
documentation: https://github.com/coval-solutions/weight-slider/blob/master/README.md

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.6.7 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4

flutter:
  uses-material-design: true
  assets:
    - images/