name: weight_slider
description: Customisable slider widget for retrieving a person's weight/mass.
version: 1.3.0-nullsafety+1
homepage: https://covalsolutions.com
repository: https://github.com/coval-solutions/weight-slider
issue_tracker: https://github.com/coval-solutions/weight-slider/issues
documentation: https://github.com/coval-solutions/weight-slider/blob/master/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0

flutter:
  uses-material-design: true
  assets:
    - images/